apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        # The DOCKER_IMAGE_TAG placeholder will be replaced by Jenkins
        image: 379632383729.dkr.ecr.ap-south-1.amazonaws.com/jenkins-demo
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
spec:
  type: LoadBalancer
  selector:
    app: simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
